name: OSINT Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      DB_NAME: ${{ secrets.DB_NAME }}
      COLLECTION_NAME: ${{ secrets.COLLECTION_NAME }}
      GROQ_API_KEY_1: ${{ secrets.GROQ_API_KEY_1 }}
      GROQ_API_KEY_2: ${{ secrets.GROQ_API_KEY_2 }}
      GROQ_API_KEY_3: ${{ secrets.GROQ_API_KEY_3 }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: pip install -r requirements.txt
      - run: python server.py